{% set name = "sofa-softrobotsinverse" %}
{% set version = "23.06.00" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/SofaDefrost/SoftRobots.Inverse/archive/refs/tags/release-v{{ major_minor }}.tar.gz
    sha256: 6eaaf58e87cf2fc8bdc09828b35142036c54f272864ec52dac5e39bceb11b6f9

build:
  number: 0
  skip: true  # [py<38]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make                           # [not win]
    - ninja                          # [win]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]

  host:
    - sofa
    - sofa-softrobots
    - sofa-stlib
    - zlib
    - eigen
    - boost-cpp

test:
  commands:
    - test -f $PREFIX/include/SoftRobots.Inverse/component/config.h                                            # [unix]
    - test -f $PREFIX/lib/cmake/SoftRobots.Inverse/SoftRobots.InverseConfig.cmake                              # [unix]
    - test -f $PREFIX/lib/cmake/SoftRobots.Inverse/SoftRobots.InverseConfigVersion.cmake                       # [unix]
    - test -f $PREFIX/lib/libSoftRobots.Inverse${SHLIB_EXT}                                                    # [unix]
    - if not exist %LIBRARY_PREFIX%\include\SoftRobots.Inverse\component\config.h exit 1                       # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\SoftRobots.Inverse\SoftRobots.InverseConfig.cmake exit 1         # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\SoftRobots.Inverse\SoftRobots.InverseConfigVersion.cmake exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\SoftRobots.Inverse.lib exit 1                                          # [win]
    - if not exist %LIBRARY_PREFIX%\bin\SoftRobots.Inverse.dll exit 1                                          # [win]

about:
  home: https://github.com/SofaDefrost/SoftRobots.Inverse
  summary: Sofa plugin containing inverse method for soft robotics.
  license: AGPL-3.0-only
  license_family: AGPL
  license_file: LICENSE.AGPLV3.txt
  dev_url: https://github.com/SofaDefrost/SoftRobots.Inverse

extra:
  recipe-maintainers:
    - olivier-roussel
    - hugtalbot
